export const USER_ROLES = {
  STAFF: "Staff",
  TEACHER: "Teacher",
  DEPARTMENT_HEAD: "Department Head",
  TECHNICAL_STAFF: "Tech Support",
  SUPER_ADMIN: "admin",
  SUPER_ADMIN_LABEL: "Super Admin",
  DEPARTMENT_ADMIN: "Tech Admin",
};

export const ROLE_GROUPS = {
  STAFF_TEACHER: [USER_ROLES.STAFF, USER_ROLES.TEACHER, USER_ROLES.DEPARTMENT_HEAD],
  TECHNICAL_STAFF: [USER_ROLES.TECHNICAL_STAFF],
  SUPER_ADMIN: [USER_ROLES.SUPER_ADMIN, USER_ROLES.SUPER_ADMIN_LABEL],
  DEPARTMENT_ADMIN: [USER_ROLES.DEPARTMENT_ADMIN],
};
